server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb+srv://gihanvidu:199884@ecanotificationdb.6lmcpdk.mongodb.net/ecanotificationdb?retryWrites=true&w=majority
      database: ecanotificationdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
